# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.User'),
        ),
    ]
