# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20171010_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('friends', models.ManyToManyField(blank=True, related_name='_facebookuser_friends_+', to='model.FacebookUser')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('following', models.ManyToManyField(to='model.InstagramUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='friends',
        ),
        migrations.DeleteModel(
            name='TwitterUser',
        ),
    ]
