# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_auto_20171010_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser',
            name='following',
            field=models.ManyToManyField(blank=True, to='model.InstagramUser'),
        ),
    ]
